- name: Request a DT OAuth access token
  ansible.builtin.uri:
    url: "{{ extra_vars.dt_oauth_sso_endpoint }}"
    method: POST
    status_code: 200
    headers:
      Content-Type: "application/x-www-form-urlencoded"
    body_format: form-urlencoded
    body:
      grant_type: "client_credentials"
      client_id: "{{ extra_vars.dt_oauth_client_id }}"
      client_secret: "{{ extra_vars.dt_oauth_client_secret }}"
      scope: "openpipeline:configurations:read openpipeline:configurations:write"
      resource: "{{ extra_vars.dt_oauth_account_urn }}"
  register: auth_response_raw
- set_fact:
    dt_oauth_access_token: "{{ auth_response_raw.json.access_token }}"

# - name: Get Configuration
#   shell: >
#     curl -X 'GET' \
#       '{{ extra_vars.dt_environment_url_gen3 }}/platform/openpipeline/v1/configurations/{id}' \ events.security, logs
#       -H 'Authorization: Bearer {{ dt_oauth_access_token }}' \
#   register: auth_response_raw
# - set_fact:
#     res: "{{ (auth_response_raw.stdout | from_json) }}"

# - name: Print variable
#   debug: "msg='{{ res }}'"

- name: Add Openpipeline Security Events Configuration
  shell: >
    curl -X 'PUT' \
      '{{ extra_vars.dt_environment_url_gen3 }}/platform/openpipeline/v1/configurations/events.security' \
      -H 'accept: application/json' \
      -H 'Content-Type: application/json' \
      -H 'Authorization: Bearer {{ dt_oauth_access_token }}' \
      -d @"/home/$USER/repos/{{path_to_openpipeline_security_events_config}}"
  register: auth_response_raw
- set_fact:
    res: "{{ auth_response_raw }}"  

- name: Print variable
  debug: "msg='{{ res }}'"